### ISSUE TITLE
Avoid styles duplication

### ISSUE THREAD

**Issue by dmtrrk** [Mariam9/simple-website#5]
DRY (https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
You have to reuse your classes instead of adding duplicates:

.center-block {
    margin: 0 auto; !!!!!!
}

.logo {
    margin: 0 auto; ?????
    .....
}

.get-app-block {
    width: 100%;
    margin: 0 auto;

---

.slogan p {
    text-align: center; ???????
    ....
}

.center-text {
    text-align: center; !!!!!!
}

**Comment by dmtrrk** [comment]
Why did you not merge these styles in .platform{ display: block }?

.apple {
    display: block; ????
}

.android {
    display: block; ????
}

**Comment by dmtrrk** [comment]
.pinterest {
    display: block; ???
        left: 1px; //are you sure this should be implemente in this way??
}
.gplus {
    display: block; ???
}

**Comment by deeptowncitizen** [comment]
So many top/left/right/bottom styles in code. You have to reduce their count because of inappropriate usage..

**Comment by Mariam9** [comment]
fixed
